##########################
##########################
## CIS LEVEL 1 SETTINGS ##
##########################
##########################

###############################
## WINDOWS FIREWALL SETTINGS ##
###############################

   - name: "9.1.1,CCE-36062-8 | Ensure 'Windows Firewall - Domain - Firewall state' is set to 'On (recommended)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
        name: "EnableFirewall"
        data: "1"
        type: dword

   - name: "9.1.2,CCE-38117-8 | Ensure 'Windows Firewall - Domain - Inbound connections' is set to 'Block (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
        name: "DefaultInboundAction"
        data: "1"
        type: dword

   - name: "9.1.3,CCE-36146-9 | Ensure 'Windows Firewall - Domain - Outbound connections' is set to 'Allow (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
        name: "DefaultOutboundAction"
        data: "0"
        type: dword

   - name: "9.1.4,CCE-38041-0 | Ensure 'Windows Firewall - Domain - Settings - Display a notification' is set to 'No'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
        name: "DisableNotifications"
        data: "1"
        type: dword

   - name: "9.1.5,CCE-37860-4 | Ensure 'Windows Firewall - Domain - Settings - Apply local firewall rules' is set to 'Yes (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
        name: "AllowLocalPolicyMerge"
        data: "1"
        type: dword

   - name: "9.1.6,CCE-38040-2 | Ensure 'Windows Firewall - Domain - Settings - Apply local connection security rules' is set to 'Yes (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
        name: "AllowLocalIPsecPolicyMerge"
        data: "1"
        type: dword

   - name: "9.1.7,CCE-37482-7 | Ensure 'Windows Firewall - Domain - Logging - Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\domainfw.log'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging
        name: "LogFilePath"
        data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\domainfw.log"
        type: string

   - name: "9.1.8,CCE-36088-3 | Ensure 'Windows Firewall - Domain - Logging - Size limit (KB)' is set to '16,384 KB or greater'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging
        name: "LogFileSize"
        data: "16384"
        type: dword

   - name: "9.1.9,CCE-37523-8 | Ensure 'Windows Firewall - Domain - Logging - Log dropped packets' is set to 'Yes'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging
        name: "LogDroppedPackets"
        data: "1"
        type: dword

   - name: "9.1.10,CCE-36393-7 | Ensure 'Windows Firewall - Domain - Logging - Log successful connections' is set to 'Yes'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging
        name: "LogSuccessfulConnections"
        data: "1"
        type: dword

   - name: "9.2.1,CCE-38239-0 | Ensure 'Windows Firewall - Private - Firewall state' is set to 'On (recommended)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile
        name: "EnableFirewall"
        data: "1"
        type: dword

   - name: "9.2.2,CCE-38042-8 | Ensure 'Windows Firewall - Private - Inbound connections' is set to 'Block (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile
        name: "DefaultInboundAction"
        data: "1"
        type: dword

   - name: "9.2.3,CCE-38332-3 | Ensure 'Windows Firewall - Private - Outbound connections' is set to 'Allow (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile
        name: "DefaultOutboundAction"
        data: "0"
        type: dword

   - name: "9.2.4,CCE-37621-0 | Ensure 'Windows Firewall - Private - Settings - Display a notification' is set to 'No'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile
        name: "DisableNotifications"
        data: "1"
        type: dword

   - name: "9.2.5,CCE-37438-9 | Ensure 'Windows Firewall - Private - Settings - Apply local firewall rules' is set to 'Yes (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile
        name: "AllowLocalPolicyMerge"
        data: "1"
        type: dword

   - name: "9.2.6,CCE-36063-6 | Ensure 'Windows Firewall - Private - Settings - Apply local connection security rules' is set to 'Yes (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile
        name: "AllowLocalIPsecPolicyMerge"
        data: "1"
        type: dword

   - name: "9.2.7,CCE-37569-1 | Ensure 'Windows Firewall - Private - Logging - Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\privatefw.log'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging
        name: "LogFilePath"
        data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\privatefw.log"
        type: string

   - name: "9.2.8,CCE-38178-0 | Ensure 'Windows Firewall - Private - Logging - Size limit (KB)' is set to '16,384 KB or greater'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging
        name: "LogFileSize"
        data: "16384"
        type: dword

   - name: "9.2.9,CCE-35972-9 | Ensure 'Windows Firewall - Private - Logging - Log dropped packets' is set to 'Yes'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging
        name: "LogDroppedPackets"
        data: "1"
        type: dword

   - name: "9.2.10,CCE-37387-8 | Ensure 'Windows Firewall - Private - Logging - Log successful connections' is set to 'Yes'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging
        name: "LogSuccessfulConnections"
        data: "1"
        type: dword

   - name: "9.3.1,CCE-37862-0 | Ensure 'Windows Firewall - Public - Firewall state' is set to 'On (recommended)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile
        name: "EnableFirewall"
        data: "1"
        type: dword

     #This control is set to Disabled (0) to allow for continued remote management of the node following machine restart
   - name: "9.3.2,CCE-36057-8 | Ensure 'Windows Firewall - Public - Inbound connections' is set to 'Block (default)'"
     win_regedit:
       path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile
       name: "DefaultInboundAction"
       data: "0" #"1"
       type: dword

   - name: "9.3.3,CCE-37434-8 | Ensure 'Windows Firewall - Public - Outbound connections' is set to 'Allow (default)'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile
        name: "DefaultOutboundAction"
        data: "0"
        type: dword

   - name: "9.3.4,CCE-38043-6 | Ensure 'Windows Firewall - Public - Settings - Display a notification' is set to 'Yes'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile
        name: "DisableNotifications"
        data: "0"
        type: dword

   - name: "9.3.5,CCE-37861-2 | Ensure 'Windows Firewall - Public - Settings - Apply local firewall rules' is set to 'No'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile
        name: "AllowLocalPolicyMerge"
        data: "0"
        type: dword

   - name: "9.3.6,CCE-36268-1 | Ensure 'Windows Firewall - Public - Settings - Apply local connection security rules' is set to 'No'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile
        name: "AllowLocalIPsecPolicyMerge"
        data: "0"
        type: dword

   - name: "9.3.7,CCE-37266-4 | Ensure 'Windows Firewall - Public - Logging - Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\publicfw.log'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging
        name: "LogFilePath"
        data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\publicfw.log"
        type: string

   - name: "9.3.8,CCE-36395-2 | Ensure 'Windows Firewall - Public - Logging - Size limit (KB)' is set to '16,384 KB or greater'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging
        name: "LogFileSize"
        data: "16384"
        type: dword

   - name: "9.3.9,CCE-37265-6 | Ensure 'Windows Firewall - Public - Logging - Log dropped packets' is set to 'Yes'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging
        name: "LogDroppedPackets"
        data: "1"
        type: dword

   - name: "9.3.10,CCE-36394-5 | Ensure 'Windows Firewall - Public - Logging - Log successful connections' is set to 'Yes'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging
        name: "LogSuccessfulConnections"
        data: "1"
        type: dword

#########
## EOF ##
#########
